### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by fischsauce** [webrecorder/webrecorderplayer-electron#66]
Hi, i'm getting this error when i try to open a .warc file:

(Running on LinuxMint 18.3, kernel 4.15.0-29-generic)

> A JavaScript error occurred in the main process
 Uncaught Exception:
Error: spawn /tmp/.mount_webrecqWCVwI/app/resources/app/python-binaries/webrecorder ENOENT
    at exports._errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

i can dismiss the error and webrecorderplayer continues to stay open, with circulating blue arrows but no content is loaded.

I then tried compiling webrecorder seperately instead of downloading from [https://s3.amazonaws.com/webrecorder-builds/webrecorder-player/develop/webrecorder-player-linux](url) but after running ./webrecorder/standalone/build_player.sh there was no output file.

**Comment by m4rk3r** [comment]
Hi @fischsauce, would it be possible to send the warc you are trying to open to support@webrecorder.io?
